/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[6];
static double forc[0];
static double cons[0];
static double eventcounter[1];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k1 parms[0] 
 #define t_e parms[1] 
 #define y0_0 parms[2] 
 #define y1_0 parms[3] 
 #define y2_0 parms[4] 
 #define y3_0 parms[5] 
#define tmin range[0]
#define tmax range[1]


void Amodel_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=6;
	 odeparms(&N, parms);
	 for(int i=0; i<1; ++i) eventcounter[i] = 0;
}

void Amodel_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void Amodel_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -k1*pow(y[0],2.0)*time;
 	 ydot[1] = (-(k1*(2.0*y[0])*time))*(y[1]);
 	 ydot[2] = (-(k1*(2.0*y[0])*time))*(y[2])-(pow(y[0],2.0)*time);
 	 ydot[3] = (-(k1*(2.0*y[0])*time))*(y[3]);

}

/** Event function **/
void Amodel_s_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == t_e & eventcounter[0] == 0) {
		y[1] = y[1] + 0;
		y[2] = y[2] + 0;
		y[3] = y[3] + 0;
		y[3] = y[3] + -(-(k1*(2.0*y[0])*time))*(1.0);
		y[0] = y[0] + 1.0;
		eventcounter[0] = eventcounter[0] + 1.;
	 }


}
