/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[12];
static double forc[0];
static double cons[0];
static double eventcounter[1];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k1 parms[0] 
 #define k2 parms[1] 
 #define y0_0 parms[2] 
 #define y1_0 parms[3] 
 #define y2_0 parms[4] 
 #define y3_0 parms[5] 
 #define y4_0 parms[6] 
 #define y5_0 parms[7] 
 #define y6_0 parms[8] 
 #define y7_0 parms[9] 
 #define y8_0 parms[10] 
 #define y9_0 parms[11] 
#define tmin range[0]
#define tmax range[1]


void vdp_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=12;
	 odeparms(&N, parms);
	 for(int i=0; i<1; ++i) eventcounter[i] = 0;
}

void vdp_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void vdp_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -k1*pow(y[0],2.0)*time;
 	 ydot[1] = k1*y[0]-k2*y[1];
 	 ydot[2] = (-(k1*(2.0*y[0])*time))*(y[2]);
 	 ydot[3] = (k1)*(y[2])+(-k2)*(y[3]);
 	 ydot[4] = (-(k1*(2.0*y[0])*time))*(y[4]);
 	 ydot[5] = (k1)*(y[4])+(-k2)*(y[5]);
 	 ydot[6] = (-(k1*(2.0*y[0])*time))*(y[6])-(pow(y[0],2.0)*time);
 	 ydot[7] = (k1)*(y[6])+(-k2)*(y[7])+y[0];
 	 ydot[8] = (-(k1*(2.0*y[0])*time))*(y[8]);
 	 ydot[9] = (k1)*(y[8])+(-k2)*(y[9])-y[1];

}

/** Event function **/
void vdp_s_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 5.0 & eventcounter[0] == 0) {
		y[2] = y[2] + 0;
		y[4] = y[4] + 0;
		y[6] = y[6] + 0;
		y[8] = y[8] + 0;
		y[0] = y[0] + 1.0;
		eventcounter[0] = eventcounter[0] + 1.;
	 }


}
