/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

extern "C" {

// Modelname: parfn
// Variables: none
// Parameters: TCA_CELL, TCA_CANA, K_IMPORT, K_EXPORT_SINUS, K_EXPORT_CANA, K_REFLUX, S
// Outputs: TCA_buffer, TCA_cell, TCA_cana, k_import, k_export_sinus, k_export_cana, k_reflux, s

void parfn_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    for (int obs = 0; obs < n_obs; obs++) {
        y[obs * n_out + 0] = 0.0;
        y[obs * n_out + 1] = std::pow(10.0, p[0]);
        y[obs * n_out + 2] = std::pow(10.0, p[1]);
        y[obs * n_out + 3] = std::pow(10.0, p[2]);
        y[obs * n_out + 4] = std::pow(10.0, p[3]);
        y[obs * n_out + 5] = std::pow(10.0, p[4]);
        y[obs * n_out + 6] = std::pow(10.0, p[5]);
        y[obs * n_out + 7] = std::pow(10.0, p[6]);
    }
}

void parfn_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 8;
    const int n_symbols = 7;

    // Zero-initialize
    std::fill(jac, jac + n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[obs, output, symbol] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * symbol)
    for (int obs = 0; obs < n_obs; obs++) {
        jac[obs + n_obs * (1 + n_out * 0)] = std::pow(10.0, p[0])*std::log(10.0);
        jac[obs + n_obs * (2 + n_out * 1)] = std::pow(10.0, p[1])*std::log(10.0);
        jac[obs + n_obs * (3 + n_out * 2)] = std::pow(10.0, p[2])*std::log(10.0);
        jac[obs + n_obs * (4 + n_out * 3)] = std::pow(10.0, p[3])*std::log(10.0);
        jac[obs + n_obs * (5 + n_out * 4)] = std::pow(10.0, p[4])*std::log(10.0);
        jac[obs + n_obs * (6 + n_out * 5)] = std::pow(10.0, p[5])*std::log(10.0);
        jac[obs + n_obs * (7 + n_out * 6)] = std::pow(10.0, p[6])*std::log(10.0);
    }
}

void parfn_hessian(double* x, double* hess, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out = 8;
    (void)n_vars;  // suppress unused warning
    const int n_symbols = 7;

    // Zero-initialize
    std::fill(hess, hess + n_obs * n_out * n_symbols * n_symbols, 0.0);

    // Layout: hess[obs, output, sym1, sym2] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * (sym1 + n_symbols * sym2))
    for (int obs = 0; obs < n_obs; obs++) {
        hess[obs + n_obs * (1 + n_out * (0 + n_symbols * 0))] = std::pow(10.0, p[0])*std::pow(std::log(10.0), 2.0);
        hess[obs + n_obs * (2 + n_out * (1 + n_symbols * 1))] = std::pow(10.0, p[1])*std::pow(std::log(10.0), 2.0);
        hess[obs + n_obs * (3 + n_out * (2 + n_symbols * 2))] = std::pow(10.0, p[2])*std::pow(std::log(10.0), 2.0);
        hess[obs + n_obs * (4 + n_out * (3 + n_symbols * 3))] = std::pow(10.0, p[3])*std::pow(std::log(10.0), 2.0);
        hess[obs + n_obs * (5 + n_out * (4 + n_symbols * 4))] = std::pow(10.0, p[4])*std::pow(std::log(10.0), 2.0);
        hess[obs + n_obs * (6 + n_out * (5 + n_symbols * 5))] = std::pow(10.0, p[5])*std::pow(std::log(10.0), 2.0);
        hess[obs + n_obs * (7 + n_out * (6 + n_symbols * 6))] = std::pow(10.0, p[6])*std::pow(std::log(10.0), 2.0);
    }
}

} // extern "C"
