#' Compile generated C++ model code
#'
#' @description
#' Compiles one or more C++ source files generated by \code{CppODE()} or
#' \code{funCpp()} into shared libraries (\code{.so}, \code{.dll}) using
#' \command{R CMD SHLIB}. Source files are located via the \code{"srcfile"}
#' attribute attached to the supplied objects.
#'
#' The function automatically applies platform-appropriate compiler flags
#' (C++17 standard, optimization, position-independent code where required)
#' and includes headers shipped with the package itself as well as Boost
#' headers provided by the \pkg{BH} package.
#'
#' On Windows, compilation is always performed sequentially since
#' fork-based parallelism is unavailable.
#'
#' @param ... One or more objects returned by \code{CppODE()} or
#'   \code{funCpp()} that carry a \code{"srcfile"} attribute pointing to an
#'   existing C or C++ source file.
#' @param output Optional base name for a combined shared library. If
#'   supplied, all provided source files are compiled and linked into a
#'   single shared object.
#' @param args Optional additional compiler or linker arguments passed to
#'   \command{R CMD SHLIB}.
#' @param cores Number of parallel compilation jobs on Unix-like systems.
#'   Ignored on Windows.
#' @param verbose Logical; if \code{TRUE}, show compiler commands and output.
#'
#' @return
#' Invisibly returns \code{TRUE} on successful compilation.
#'
#' @keywords internal
#' @import BH
compile <- function(..., output = NULL, args = NULL, cores = 1, verbose = FALSE) {

  ## save & restore env
  old <- Sys.getenv(c("PKG_CFLAGS", "PKG_CXXFLAGS", "PKG_CPPFLAGS"), unset = NA)
  on.exit({
    for (n in names(old))
      if (is.na(old[n])) Sys.unsetenv(n) else Sys.setenv(structure(old[n], names = n))
  }, add = TRUE)

  objects <- list(...)
  Rbin <- shQuote(file.path(R.home("bin"), "R"))
  so   <- .Platform$dynlib.ext

  # --- collect source files via srcfile attribute ---
  files <- unique(unlist(lapply(objects, function(obj) {
    src <- attr(obj, "srcfile")
    if (!is.null(src) && file.exists(src))
      normalizePath(src, winslash = "/", mustWork = FALSE)
  })))

  if (!length(files))
    stop("No valid C/C++ source files found for compilation.")

  roots <- sub("\\.[^.]+$", "", basename(files))

  # --- compiler flags ---
  if (.Platform$OS.type == "windows") cores <- 1

  pic  <- if (.Platform$OS.type == "windows") "" else "-fPIC"
  base <- paste("-O2 -DNDEBUG -w", pic)
  if (!is.null(args) && nzchar(args)) base <- paste(base, args)

  Sys.setenv(
    PKG_CXXFLAGS = base,
    PKG_CPPFLAGS = paste(
      paste0("-I", system.file("include", package = "CppODE")),
      paste0("-I", system.file("include", package = "BH"))
    )
  )

  # --- toolchain report ---
  cfg   <- function(x) system(paste(Rbin, "CMD config", x), intern = TRUE)
  strip <- function(x) trimws(gsub("(^| )-std=[^ ]+", "", x))

  if (any(grepl("\\.cpp$", files)))
    cat(sprintf("using C++ compiler: %s [%s]\n",
                strip(cfg("CXX")), trimws(Sys.getenv("PKG_CXXFLAGS"))))

  # --- unload old libraries ---
  invisible(lapply(c(roots, output), function(x) {
    if (!is.null(x)) try(dyn.unload(paste0(x, so)), silent = TRUE)
  }))

  # --- helper: run R CMD SHLIB ---
  run <- function(cmd) {
    if (verbose) cat(cmd, "\n")
    if (system(cmd, ignore.stdout = !verbose, ignore.stderr = !verbose) != 0)
      stop("Compilation failed")
  }

  # --- compile ---
  if (is.null(output)) {
    if (.Platform$OS.type == "unix" && cores > 1)
      parallel::mclapply(files, function(f) run(paste(Rbin, "CMD SHLIB", shQuote(f))), mc.cores = cores)
    else
      for (f in files) run(paste(Rbin, "CMD SHLIB", shQuote(f)))
    for (r in roots) dyn.load(paste0(r, so))
  } else {
    output <- sub(paste0("\\", so, "$"), "", output)
    outdir <- dirname(files[1])
    out_so <- file.path(outdir, paste0(output, so))

    try(dyn.unload(out_so), silent = TRUE)
    if (file.exists(out_so)) unlink(out_so)

    run(paste(Rbin, "CMD SHLIB",
              paste(shQuote(files), collapse = " "),
              "-o", shQuote(out_so)))

    dyn.load(out_so)
  }

  invisible(TRUE)
}
