#' Compile generated C++ model code
#'
#' @description
#' Compiles one or more C++ source files generated by [CppODE()] or
#' [funCpp()] into shared libraries (`.so`, `.dll`) using
#' `R CMD SHLIB`.
#'
#' Compile-time flags stored in the `"compileArgs"` attribute of each
#' object (e.g. `-DCPPODE_PROFILE`, KLU tuning defines) are picked up
#' automatically.  Additional flags may be passed via `args`.
#'
#' @param ... One or more objects returned by [CppODE()] or
#'   [funCpp()] that carry a `"srcfile"` attribute.
#' @param output Optional base name for a combined shared library.
#' @param args Optional additional compiler or linker arguments appended
#'   after the flags from `"compileArgs"`.
#' @param cores Number of parallel compilation jobs (Unix only).
#' @param verbose Logical; if `TRUE`, show compiler commands.
#'
#' @return Invisibly returns `TRUE` on successful compilation.
#' @keywords internal
compile <- function(..., output = NULL, args = NULL, cores = 1, verbose = FALSE) {

  ## save & restore env
  old <- Sys.getenv(c("PKG_CFLAGS", "PKG_CXXFLAGS", "PKG_CPPFLAGS", "PKG_LIBS"), unset = NA)
  on.exit({
    for (n in names(old))
      if (is.na(old[n])) Sys.unsetenv(n) else Sys.setenv(structure(old[n], names = n))
  }, add = TRUE)

  objects <- list(...)
  Rbin <- shQuote(file.path(R.home("bin"), "R"))
  so   <- .Platform$dynlib.ext

  # --- collect source files ---
  files <- unique(unlist(lapply(objects, function(obj) {
    src <- attr(obj, "srcfile")
    if (!is.null(src) && file.exists(src))
      normalizePath(src, winslash = "/", mustWork = FALSE)
  })))
  if (!length(files))
    stop("No valid C/C++ source files found for compilation.")

  roots      <- sub("\\.[^.]+$", "", basename(files))
  roots_full <- sub("\\.[^.]+$", "", files)

  # --- merge compileArgs from objects with explicit args ---
  obj_args <- unique(unlist(lapply(objects, function(obj) {
    a <- attr(obj, "compileArgs")
    if (!is.null(a) && nzchar(a)) a else NULL
  })))
  all_args <- paste(c(obj_args, args), collapse = " ")

  # --- extra linker flags from objects (linkArgs) ---
  obj_linkargs <- unique(unlist(lapply(objects, function(obj) {
    a <- attr(obj, "linkArgs")
    if (!is.null(a) && nzchar(a)) a else NULL
  })))
  extra_libs <- paste(obj_linkargs, collapse = " ")

  # --- compiler flags ---
  if (.Platform$OS.type == "windows") cores <- 1
  pic  <- if (.Platform$OS.type == "windows") "" else "-fPIC"
  base <- paste("-O2 -DNDEBUG -w", pic)

  # --- LAPACK (always available via R) ---
  cfg <- function(x) trimws(system(paste(Rbin, "CMD config", x), intern = TRUE))
  lapack_libs <- cfg("LAPACK_LIBS")
  blas_libs   <- cfg("BLAS_LIBS")

  # --- KLU (system SuiteSparse, discovered by ./configure at install) ---
  uses_sparse <- any(vapply(objects, function(obj) {
    isTRUE(attr(obj, "sparse"))
  }, logical(1)))

  klu_libs   <- ""
  klu_cflags <- ""

  if (uses_sparse) {
    if (!isTRUE(cvodeConfig$klu_available)) {
      stop(
        "Sparse Jacobian requested but the KLU linear solver was not\n",
        "available at install time. Install SuiteSparse development\n",
        "headers and re-install CppODE:\n",
        "    Debian/Ubuntu : sudo apt install libsuitesparse-dev\n",
        "    Fedora        : sudo dnf install suitesparse-devel\n",
        "    Arch          : sudo pacman -S suitesparse\n",
        "    macOS (brew)  : brew install suite-sparse\n",
        "    Windows       : from any shell (PowerShell / cmd / Git Bash)\n",
        "                    call Rtools' pacman by full path -- substitute\n",
        "                    your installed version for <ver> (e.g. 44 or 45):\n",
        "                      C:/rtools<ver>/usr/bin/pacman.exe -Sy --noconfirm mingw-w64-ucrt-x86_64-suitesparse\n",
        "  Then: R CMD INSTALL <path/to/CppODE>",
        call. = FALSE)
    }
    klu_cflags <- paste("-DKLU", cvodeConfig$klu_cflags)
    klu_libs   <- cvodeConfig$klu_libs
  }

  cxxflagsString <- paste(base, klu_cflags)
  if (nzchar(all_args)) cxxflagsString <- paste(cxxflagsString, all_args)
  Sys.setenv(
    PKG_CXXFLAGS = cxxflagsString,
    PKG_CPPFLAGS = paste0("-I", system.file("include", package = "CppODE")),
    PKG_LIBS = paste(klu_libs, lapack_libs, blas_libs, extra_libs)
  )

  # --- toolchain report ---
  strip <- function(x) trimws(gsub("(^| )-std=[^ ]+", "", x))
  if (any(grepl("\\.cpp$", files)))
    cat(sprintf("using C++ compiler: %s [%s]\n",
                strip(cfg("CXX")), trimws(Sys.getenv("PKG_CXXFLAGS"))))

  # --- unload stale DLLs ---
  unload_and_delete <- function(basename_no_ext, so_path) {
    loaded <- getLoadedDLLs()
    if (basename_no_ext %in% names(loaded))
      try(dyn.unload(loaded[[basename_no_ext]][["path"]]), silent = TRUE)
    if (file.exists(so_path)) try(unlink(so_path), silent = TRUE)
  }

  if (is.null(output)) {
    invisible(mapply(unload_and_delete,
                     roots, paste0(roots_full, so),
                     SIMPLIFY = FALSE))
  } else {
    try(dyn.unload(paste0(output, so)), silent = TRUE)
  }

  # --- compile ---
  run <- function(cmd) {
    if (verbose) cat(cmd, "\n")
    if (system(cmd, ignore.stdout = !verbose, ignore.stderr = !verbose) != 0)
      stop("Compilation failed")
  }

  if (is.null(output)) {
    if (.Platform$OS.type == "unix" && cores > 1)
      parallel::mclapply(files, function(f)
        run(paste(Rbin, "CMD SHLIB", shQuote(f))), mc.cores = cores)
    else
      for (f in files) run(paste(Rbin, "CMD SHLIB", shQuote(f)))
    for (r in roots_full) dyn.load(paste0(r, so))
  } else {
    output <- sub(paste0("\\", so, "$"), "", output)
    outdir <- dirname(files[1])
    out_so <- file.path(outdir, paste0(output, so))
    try(dyn.unload(out_so), silent = TRUE)
    if (file.exists(out_so)) unlink(out_so)
    run(paste(Rbin, "CMD SHLIB",
              paste(shQuote(files), collapse = " "),
              "-o", shQuote(out_so)))
    dyn.load(out_so)
  }

  invisible(TRUE)
}
